### ISSUE TITLE
error: unhandled error

### ISSUE THREAD

**Issue by michielibiza** [vigour-io/vigour-img#25]
sometimes get this error in the android build of vigour-example

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Path must be a string without null bytes.
    at nullCheck (evalmachine.<anonymous>:107:14)
    at Object.fs.open (evalmachine.<anonymous>:486:8)
    at OpenReq.process (/Users/michielvanliempt/coding/vigour/vigour-example/node_modules/vigour-native/node_modules/vigour-fs/node_modules/graceful-fs/graceful-fs.js:53:16)
    at OpenReq.Req (/Users/michielvanliempt/coding/vigour/vigour-example/node_modules/vigour-native/node_modules/vigour-fs/node_modules/graceful-fs/graceful-fs.js:124:8)
    at new OpenReq (/Users/michielvanliempt/coding/vigour/vigour-example/node_modules/vigour-native/node_modules/vigour-fs/node_modules/graceful-fs/graceful-fs.js:47:7)
    at Object.open (/Users/michielvanliempt/coding/vigour/vigour-example/node_modules/vigour-native/node_modules/vigour-fs/node_modules/graceful-fs/graceful-fs.js:39:3)
    at WriteStream.open (evalmachine.<anonymous>:1770:6)
    at new WriteStream (evalmachine.<anonymous>:1760:10)
    at Object.fs.createWriteStream (evalmachine.<anonymous>:1724:10)
    at IncomingMessage.<anonymous> (/Users/michielvanliempt/coding/vigour/vigour-example/node_modules/vigour-native/node_modules/vigour-img/lib/launcher.js:450:27)
    at IncomingMessage.emit (events.js:107:17)
    at IncomingMessage.Readable.read (_stream_readable.js:373:10)
    at flow (_stream_readable.js:750:26)
    at resume_ (_stream_readable.js:730:3)
    at _stream_readable.js:717:7
    at process._tickCallback (node.js:355:11)
```

**Comment by shawninder** [comment]
@michielibiza Did you see this again recently?

**Comment by michielibiza** [comment]
I don't know I haven't tried for a while. I'm waiting with builds until you're ready with your stuff :)
When `vigour-native` and `vigour-example` are in a state that we can build with `statusbar` and `env`, then I come back to the build process.

**Comment by shawninder** [comment]
The builds are working well for me on my new branch (feature/test-app) You can check it out. I intend to merge that branch into develop today, just need to fix a couple bugs
